name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name nbaplayoffpredictions \
            --destination '$web' \
            --source . \
            --overwrite
