name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name nbaplayoffpredictions \
              --destination '$web' \
              --source . \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --overwrite
